quarkus:
  package.type: uber-jar
  http:
    port: 8061
    cors: true
    test-port: 6061

coordinates:
  defaults:
    # default size of fetched data
    size: 8
    # search center
    center:
      lat: 50.77
      lng: 19.77