apiVersion: apps/v1
kind: Deployment
metadata:
  name: illegal-dump-coordinates
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinates
  template:
    metadata:
      labels:
        app: coordinates
    spec:
      containers:
        - name: coordinates
          image: 0i99/illegal-dump-coordinates
          ports:
            - containerPort: 8061
          env:
            - name: QUARKUS_PROFILE
              value: prd-k8

---

apiVersion: v1
kind: Service
metadata:
  name: illegal-dump-coordinates
spec:
  type: NodePort
  ports:
    - port: 8061
#      targetPort: 8061
      nodePort: 30061
      protocol: TCP
      name: http
  selector:
    app: coordinates