openapi: 3.0.1
info:
  description: "API for coordinates"
  version: "0.0.1"
  title: "Coordinates API"
  contact:
    email: "0i99@pm.me"
  license:
    name: "MIT license"
    url: "https://github.com/illegal-dump/coordinates/blob/main/LICENSE"
paths:
  /api/coordinates:
    get:
      tags:
        - "coordinates"
      summary: "get coordinates"
      operationId: getCCoordinates
      parameters:
        - in: query
          description: "center lat"
          name: lat
          required: false
          schema:
            type: number
        - in: query
          description: "center lng"
          name: lng
          required: false
          schema:
            type: number
        - in: query
          description: "size"
          name: size
          required: false
          schema:
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoordinateRspDto'
          description: "OK"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "422":
          description: "General error"
components:
  schemas:
    CoordinateDto:
      type: "object"
      required:
        - "lat"
        - "lng"
      properties:
        lat:
          type: number
          default: 50.23
        lng:
          type: number
          default: 19.02
        label:
          description: "label"
          type: string
          default: "something"
    CoordinateRspDto:
      type: "object"
      required:
        - "coordinates"
      properties:
        coordinates:
          type: array
          items:
            $ref: '#/components/schemas/CoordinateDto'




